on:
  # push:
  workflow_dispatch:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  display_files:
    name: Job name display file content
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Display file content
        run: |
          cat test.txt
        shell: bash
